### ISSUE TITLE
Add Code Comments?

### ISSUE THREAD

**Issue by Ryanshuai** [Ryanshuai/BM3D_py#3]
Thanks for your work! Can you write more comments to your code ?

_Originally posted by @442413768 in https://github.com/Ryanshuai/BM3D_cpp2py/issues/1#issuecomment-559799631_

**Comment by Ryanshuai** [comment]
Yes, I will add code comments someday.
Maybe I will also write a blog to demonstrate all the details of the code.
I'm very busy right now, the code is much clearer than the original CPP code, and you can debug it for details.

**Comment by Ryanshuai** [comment]
I have added some notes in almost every file.
Ask me if you guys want more.

**Comment by Dreamscape315** [comment]
十分期待您可以写一篇博客详解您的代码
