### ISSUE TITLE
a question about the precompute_BM

### ISSUE THREAD

**Issue by sjames40** [Ryanshuai/BM3D_py#6]
I want to ask a question about the function of the Precompute_Bm and explain a little bit of the algorithm behind it. I understand the way is trying to roll the image in order to get the difference between the patch and then sorting it into the sum_table and hard thresholding to get the position of the patch? is that correct?

**Comment by Ryanshuai** [comment]
There is no hard threshold in this file.
The threshold here is to limit a maximum distance between the referenced patch and nearby patches.
The distance between two patches is defined as the square root of the sum of all square of the pix-wise differences.
Hope this will help you understand it.

**Comment by Ryanshuai** [comment]
If distance is bigger than the threshold, then the nearby patch is not similar to the referenced patch.
Then it won't be added to the 3D block and it won't participate in the filter process which means it doesn't influence the denoising result.

**Comment by sjames40** [comment]
I am still a little confused about what the is the function of the row_add_mat and column_add_mat doing

Thank you

**Comment by Ryanshuai** [comment]
> I am still a little confused about what the is the function of the row_add_mat and column_add_mat doing
> 
> Thank you

It is just a matrix trick to add all the square of the differences in a patch size up.
You may want to check linear algebra to see what is going on here.

**Comment by sjames40** [comment]
sorry for bothering you, I just have one more question about the function different margin. is that trying the zero out the patch that in the outside of the matrix because it is a matrix which center is 1 and outside is zero

Thank you

**Comment by Ryanshuai** [comment]
> sorry for bothering you, I just have one more question about the function different margin. is that trying the zero out the patch that in the outside of the matrix because it is a matrix which center is 1 and outside is zero
> 
> Thank you

Yeah, it is. I can't remember all the detail. I do it as the C++ code does. You can try to debug it for detail.
Don't be worry, ask if you have to. I know how frustrating when you are reading others' code.

**Comment by sjames40** [comment]
yes, I ask you a lot of questions because I am trying to modify it in order to implement my research result which needed to use the DCT matrix in the block matching function which it doesn't have in the code. Furthermore, Thank you for your helping
