### ISSUE TITLE
Such a clever technique

### ISSUE THREAD

**Issue by WanShaw** [Ryanshuai/BM3D_py#9]
How do you think of using np.roll and Identity matrix to achieve the difference in similarity across the picture?
In precompute_BM.py, function get_add_patch_matrix use it.

**Comment by Ryanshuai** [comment]
Hi WanShaw,
Glad to hear that~
CNN uses a similar technique to calculate the convolution of features.
You can refer to my other repository, https://github.com/Ryanshuai/NumPy_CNN/blob/master/layers/Conv/Conv.py

**Comment by WanShaw** [comment]
Thank you for your answer!
